COMPANY_SOURCES = [
    # Germany-focused / likely targets
    {
        "id": 1,
        "name": "Celonis",
        "provider": "greenhouse",
        "board_token": "celonis",
        "location_hint": "Germany",
    },
    {
        "id": 2,
        "name": "DeepL",
        "provider": "ashby",
        "organization_slug": "deepl",
        "location_hint": "Germany",
    },
    {
        "id": 3,
        "name": "Aleph Alpha",
        "provider": "custom",
        "careers_url": "https://aleph-alpha.jobs.personio.com/",
        "location_hint": "Germany",
    },
    {
        "id": 4,
        "name": "SAP",
        "provider": "custom",
        "careers_url": "https://jobs.sap.com/",
        "location_hint": "Germany",
    },
    {
        "id": 5,
        "name": "Siemens",
        "provider": "custom",
        "careers_url": "https://jobs.siemens.com/careers",
        "location_hint": "Germany",
    },
    {
        "id": 6,
        "name": "BMW Group",
        "provider": "custom",
        "careers_url": "https://www.bmwgroup.jobs/",
        "location_hint": "Germany",
    },
    {
        "id": 7,
        "name": "Mercedes-Benz Group",
        "provider": "custom",
        "careers_url": "https://jobs.mercedes-benz.com/",
        "location_hint": "Germany",
    },
    {
        "id": 8,
        "name": "Bosch",
        "provider": "custom",
        "careers_url": "https://jobs.bosch.com/",
        "location_hint": "Germany",
    },
    {
        "id": 9,
        "name": "Deutsche Telekom",
        "provider": "custom",
        "careers_url": "https://www.telekom.com/en/careers",
        "location_hint": "Germany",
    },
    {
        "id": 10,
        "name": "Airbus",
        "provider": "custom",
        "careers_url": "https://www.airbus.com/en/careers",
        "location_hint": "Germany",
    },
    {
        "id": 11,
        "name": "Amazon",
        "provider": "custom",
        "careers_url": "https://www.amazon.jobs/",
        "location_hint": "Germany",
    },
    {
        "id": 12,
        "name": "Microsoft",
        "provider": "custom",
        "careers_url": "https://jobs.careers.microsoft.com/",
        "location_hint": "Germany",
    },
    {
        "id": 13,
        "name": "Google",
        "provider": "custom",
        "careers_url": "https://www.google.com/about/careers/applications/jobs/results/",
        "location_hint": "Germany",
    },
    {
        "id": 14,
        "name": "NVIDIA",
        "provider": "custom",
        "careers_url": "https://nvidia.wd5.myworkdayjobs.com/NVIDIAExternalCareerSite",
        "location_hint": "Germany",
    },
    {
        "id": 15,
        "name": "Databricks",
        "provider": "lever",
        "account": "databricks",
        "location_hint": "Germany",
    },
    {
        "id": 16,
        "name": "MongoDB",
        "provider": "greenhouse",
        "board_token": "mongodb",
        "location_hint": "Germany",
    },
    {
        "id": 17,
        "name": "Dataiku",
        "provider": "greenhouse",
        "board_token": "dataiku",
        "location_hint": "Germany",
    },
    {
        "id": 18,
        "name": "LILT",
        "provider": "greenhouse",
        "board_token": "lilt",
        "location_hint": "Germany",
    },
    {
        "id": 19,
        "name": "NewStore",
        "provider": "greenhouse",
        "board_token": "newstore",
        "location_hint": "Germany",
    },
    {
        "id": 20,
        "name": "Benchling",
        "provider": "greenhouse",
        "board_token": "benchling",
        "location_hint": "Germany",
    },
    {
        "id": 21,
        "name": "Apple",
        "provider": "custom",
        "careers_url": "https://jobs.apple.com/",
        "location_hint": "Germany",
    },
    {
        "id": 22,
        "name": "Meta",
        "provider": "custom",
        "careers_url": "https://www.metacareers.com/jobs/",
        "location_hint": "Germany",
    },
    {
        "id": 23,
        "name": "Tesla",
        "provider": "custom",
        "careers_url": "https://www.tesla.com/careers/search",
        "location_hint": "Germany",
    },
    {
        "id": 24,
        "name": "Volkswagen Group",
        "provider": "custom",
        "careers_url": "https://www.volkswagen-group.com/en/career-15812",
        "location_hint": "Germany",
    },
    {
        "id": 25,
        "name": "KONUX",
        "provider": "custom",
        "careers_url": "https://konux.com/careers/",
        "location_hint": "Germany",
    },
    {
        "id": 26,
        "name": "Hawk AI",
        "provider": "custom",
        "careers_url": "https://hawk.ai/company/careers/",
        "location_hint": "Germany",
    },
    {
        "id": 27,
        "name": "Black Forest Labs",
        "provider": "custom",
        "careers_url": "https://blackforestlabs.ai/",
        "location_hint": "Germany",
    },
    {
        "id": 28,
        "name": "Dida",
        "provider": "custom",
        "careers_url": "https://dida.do/careers",
        "location_hint": "Germany",
    },
    {
        "id": 29,
        "name": "TwentyBN",
        "provider": "custom",
        "careers_url": "https://www.qualcomm.com/company/careers",
        "location_hint": "Germany",
    },
    {
        "id": 30,
        "name": "OpenAI",
        "provider": "custom",
        "careers_url": "https://openai.com/careers/",
        "location_hint": "Germany",
    },
]